name: setcovering
inst_name: setcovering_preprocessed
n_objs: 3
n_vars: 100
n_cons: 20
n_vars_per_con: 10
size: ${problem.n_vars}_${problem.n_objs}
n_max_vars: ${problem.n_vars}
n_max_objs: ${problem.n_objs}
n_features: 37
n_weights: 7
acronym: bp
id: 3
# Control bandwidth minimization
# Options: 0 | 1
preprocess: 0