defaults:
  - problem: setpacking
  - _self_


from_pid: 0
to_pid: 1
# train | val
split: train

# canonical: default ordering [0, ..., n-1]
# rand: random ordering based on fixed seeds
# min_weight: Ascending order of weight
order_type: canonical

seed:
  opt: 7
  smac: 777

smac_dir:
smac_all_dir: kp_7_3_60_0

bdd:
  # In seconds
  timelimit: 600
  # In GBs
  memlimit: 5
  # Boolean: 0 or 1
  mask_memlimit: 0

res_path:
  cc: /home/rahulpat/scratch/l2o_resources/
  desktop: /home/rahul/Documents/projects/multiobjective_cp2016/python/learn2rank/resources
  laptop: /home/rahul/Documents/PhD/projects/multiobjective_cp2016/python/learn2rank/resources
machine: laptop

case: 0
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${case}
