defaults:
  - problem: knapsack
  - _self_

from_pid: 0
to_pid: 1
# train | val
split: train

res_path:
  cc: /home/rahulpat/scratch/l2o_resources/
  desktop: /home/rahul/Documents/projects/multiobjective_cp2016/resources
  laptop: /home/rahul/Documents/projects/multiobjective_cp2016/resources

machine: desktop

pred:
  name: linreg_predictions_5_40.pkl

bdd:
  timelimit: 300
  memlimit:

case: 0
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${case}
