defaults:
  - problem: knapsack
  - _self_

from_pid: 0
to_pid: 1
# train | val
split: train

res_path:
  cc: /home/rahulpat/scratch/l2o_resources/
  desktop: /home/rahul/Documents/projects/multiobjective_cp2016/resources
  laptop: /home/rahul/Documents/PhD/projects/multiobjective_cp2016/resources

machine: desktop

inst_path: ${res_path[${machine}]}/instances/${problem.inst_name}
pred_path: ${res_path[${machine}]}/predictions/${problem.name}/${problem.size}
best_model_summary_path: ${res_path[${machine}]}/model_summary/${problem.name}/best_model_${problem.size}
eval_order_path: ${res_path[${machine}]}/eval_order/${problem.name}/${problem.size}

model_name: GradientBootingRegressor
task: point_regress

bdd:
  timelimit: 1800
  memlimit: 16

case: 0
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${case}
