defaults:
  - problem: knapsack
  - _self_


res_path:
  cc: /home/rahulpat/scratch/l2o_resources/
  desktop: /home/rahul/Documents/projects/multiobjective-bdd-vo/resources
  laptop: /home/rahul/Documents/PhD/projects/multiobjective-bdd-vo/resources


machine: desktop

output_dir: ${res_path[${machine}]}/predictions/${problem.name}
summary_path: ${res_path[${machine}]}/model_summary/${problem.name}
model_selection: k-tau