defaults:
  - _self_
  - featurizer: knapsack
  - problem: knapsack

res_path:
  cc: /home/rahulpat/scratch/l2o_resources/
  desktop: /home/rahul/Documents/projects/multiobjective_cp2016/resources
  laptop: /home/rahul/Documents/PhD/projects/multiobjective_cp2016/resources

machine: desktop

padding: False