problem:
  name: knapsack
  size: '4_50'

all_run_ids:
  '5_40':
    - '777'
  '6_40':
    - '777'
  '7_40':
    - '777'
  '4_50': ${run_ids_dump}
  '3_60': ${run_ids_dump}
  '3_70': ${run_ids_dump_3_70}
  '3_80': ${run_ids_dump}
run_ids: ${all_run_ids[${problem.size}]}
n_run_ids: 5

all_cutoff:
  '5_40': 300
  '6_40': 1200
  '7_40': 1200
  '4_50': 300
  '3_60': 300
  '3_70': 1200
  '3_80': 1200
cutoff: ${all_cutoff[${problem.size}]}

all_wallclock:
  '5_40': 300
  '6_40': 1200
  '7_40': 1200
  '4_50': 300
  '3_60': 300
  '3_70': 1200
  '3_80': 1200
wallclock: ${all_wallclock[${problem.size}]}

machine: desktop
res_path:
  cc: /home/rahulpat/scratch/l2o_resources/
  desktop: /home/rahul/Documents/projects/multiobjective_cp2016/resources
  laptop: /home/rahul/PhD/Documents/projects/multiobjective_cp2016/resources
label_path: ${res_path[${machine}]}/labels/${problem.name}/${problem.size}
smac_run_path: ${res_path[${machine}]}/smac_output/${problem.name}/iinc_min_weight/${problem.size}


run_ids_dump:
  - '578'
  - '470'
  - '1337'
  - '3345'
  - '983439'
  - '329'
  - '1021'
  - '4321'
  - '7623'
  - '5621'
  - '271'
  - '82'
  - '3336'
  - '813'
  - '774'
  - '9194'
  - '2127'
  - '5104'
  - '7746'
  - '2401'
  - '76'
  - '5475'
  - '7557'
  - '5958'
  - '6348'
  - '7766'
  - '843'
  - '533'
  - '8496'
  - '1234'
  - '7186'
  - '7987'
  - '1245'
  - '2959'
  - '8946'
  - '571'
  - '6654'
  - '9314'
  - '7144'
  - '7179'
  - '3198'
  - '854'
  - '7774'
  - '5953'
  - '4226'
  - '2857'
  - '2020'
  - '1253'
  - '8695'
  - '8385'

run_ids_dump_3_70:
  - '588'
  - '480'
  - '1347'
  - '3355'
  - '983449'
  - '339'
  - '1031'
  - '4331'
  - '7633'
  - '5631'
  - '281'
  - '92'
  - '3346'
  - '823'
  - '784'
  - '9204'
  - '2137'
  - '5114'
  - '7756'
  - '2411'
  - '86'
  - '5485'
  - '7567'
  - '5968'
  - '6358'
  - '7776'
  - '7853'
  - '543'
  - '8506'
  - '1244'
  - '7196'
  - '7997'
  - '1255'
  - '2969'
  - '8956'
  - '581'
  - '6664'
  - '9324'
  - '7154'
  - '7189'
  - '3208'
  - '864'
  - '7784'
  - '5963'
  - '4236'
  - '2867'
  - '2030'
  - '1263'
  - '8705'
  - '8395'