defaults:
  - _self_
  - featurizer: knapsack
  - problem: knapsack

# Flag to decide if we want to create a single dataset
# for all sizes
fused:

size:
  - '5_40'
  - '6_40'
  - '7_40'
  - '4_50'
  - '3_60'
  - '3_70'
  - '3_80'


split:
  - 'train'
  - 'val'
  - 'test'

normalize_rank: 0

# Initial incumbent
iinc: min_weight

# Task for which you want to generate the dataset
# Options:
# 1. point_regress: Generates dataset to do pointwise regression
# 2. pair_rank: Generates pairwise ranking dataset for a fixed size
# 3. pair_rank_all: Generates pairwise ranking dataset for all sizes
# 4. pair_rank_all_context: Generates pairwise ranking dataset for all sizes with context features
# 5. multitask: Generates dataset for the multitask learning. Stores the cost
#               and config along with rank
task: point_regress

padding: False

res_path:
  cc: /home/rahulpat/scratch/l2o_resources/
  desktop: /home/rahul/Documents/projects/multiobjective_cp2016/resources
  laptop: /home/rahul/Documents/PhD/projects/multiobjective_cp2016/resources

out_path:
  cc: /home/rahulpat/scratch/l2o_resources
  desktop: /home/rahul/Documents/projects/multiobjective_cp2016
  laptop: /home/rahul/Documents/PhD/projects/multiobjective_cp2016

machine: desktop

hydra:
  run:
    dir: ${out_path[${machine}]}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
