defaults:
  - hydra: train
  - problem: knapsack
  - model: LinearRegression
  - optimizer: adam
  - run: default
  - wandb: default
  - _self_

# Type of ranking task
# pointwise, pairwise or listwise
task: point_regress

res_path:
  cc: /home/rahulpat/scratch/l2o_resources/
  desktop: /home/rahul/Documents/projects/multiobjective_cp2016/resources
  laptop: /home/rahul/PhD/Documents/projects/multiobjective_cp2016/resources
machine: desktop

dataset:
  path: ${res_path[${machine}]}/datasets/${problem.name}/${problem.name}_dataset_${task}.pkl
  size:
    - '4_50'

case: 0
output_dir: ${hydra:runtime.output_dir}