# A configurable BDD variable ranking model called Neural Ranking Machine
name: NeuralRankingMachine
# Trainer used to run this model
trainer: PyTorchTrainer

# Feature encoder network params
feat_enc:
  layers:
    - 37
    - 128
  act: ReLU
  dp: 0


# Transformer-encoder params
tf_enc:
  switch: True
  d_model: 128
  n_heads: 4
  d_ff: 256
  dp: 0.1
  act: gelu
  n_layers: 3

# Set-encoder params
set_enc:
  mlp:
    layers:
      - 128
      - 256
    act: ReLU
    dp: 0.1
  agg_type: sum

# Rank predictor network params
rp:
  switch: True
  mlp:
    layers:
      - 128
      - 1
    act: Sigmoid
    dp: 0
  loss_fn: PointwiseRMSELoss

# Weight predictor network params
wp:
  switch: False
  mlp:
    layers:
      - 256
      - 18
    act: Tanh
    dp: 0
  loss_fn: RMSE


# Time predictor network params
tp:
  switch: False
  mlp:
    layers:
      - 256
      - 1
    act: Sigmoid
    dp: 0
  loss_fn: RMSE
