problem:
  name: knapsack

from_pid: 0
to_pid: 1
# train | val
split: train
case: 0

pred:
  name: linreg_predictions.pkl

bdd:
  timelimit: 60
  memlimit:

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${case}
