problem:
  name: knapsack
  n_objs: 3
  n_vars: 60
  size: ${problem.n_objs}_${problem.n_vars}

from_pid: 0
to_pid: 1
# train | val
split: train
case: 0

# canonical: default ordering [0, ..., n-1]
# rand: random ordering based on fixed seeds
# min_weight: Ascending order of weight
order_type: canonical

bdd:
  timelimit: 300
  memlimit:

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${case}
