defaults:
  - _self_
  - problem: knapsack
  - model: nrm
  - optimizer: adam

# Trainer parameters
run:
  # Number of training epochs
  n_epochs: 2
  # Batch size used for training model
  batch_size: 32
  # Lasso penalty weight
  wt_lasso: 0
  # Ridge penalty weight
  wt_ridge: 0
  # Seeds for reproducibility
  seed: 1501

# Use wandb for saving results to cloud
wandb:
  project: dd-ranking
  mode: disabled
