defaults:
  - _self_
  - problem: knapsack
  - model: nrm
  - optimizer: adam

case: 0
output_dir: ${hydra:runtime.output_dir}

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${case}

# Trainer parameters
run:
  # Number of training epochs
  n_epochs: 2
  # Batch size used for training model
  batch_size: 32
  # Lasso penalty weight
  wt_lasso: 0
  # Ridge penalty weight
  wt_ridge: 0
  # Seeds for reproducibility
  seed: 1501

# Use wandb for saving results to cloud
wandb:
  project: dd-ranking
  mode: disabled
